version: '3.8'

services:
  server:
    image: 'disctimeo-spring:latest'
    build:
      context: .
    container_name: server
    depends_on:
      - db
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/$POSTGRES_DB
      - SPRING_DATASOURCE_USERNAME=$SPRING_DATASOURCE_USERNAME
      - SPRING_DATASOURCE_PASSWORD=$SPRING_DATASOURCE_PASSWORD
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 8080:8080

  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - 5432:5432
    volumes: -postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}
